/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApiKeysCreateApiKeyRequest {
    /// The label of the new API Key
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// The permissions granted to this API Key (See API Key Authentication)
    #[serde(rename = "permissions", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<Vec<String>>,
}

impl ApiKeysCreateApiKeyRequest {
    pub fn new() -> ApiKeysCreateApiKeyRequest {
        ApiKeysCreateApiKeyRequest {
            label: None,
            permissions: None,
        }
    }
}


