/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApplicationHealthData {
    /// True if the instance is fully synchronized, according to NBXplorer
    #[serde(rename = "synchronized", skip_serializing_if = "Option::is_none")]
    pub synchronized: Option<bool>,
}

impl ApplicationHealthData {
    pub fn new() -> ApplicationHealthData {
        ApplicationHealthData {
            synchronized: None,
        }
    }
}


