/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ApplicationServerInfoNodeStatusData : Detailed sync status of the internal full node



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApplicationServerInfoNodeStatusData {
    /// The height of the chain of header of the internal full node
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<i32>,
    /// The height of the latest validated block of the internal full node
    #[serde(rename = "blocks", skip_serializing_if = "Option::is_none")]
    pub blocks: Option<i32>,
    /// The current synchronization progress
    #[serde(rename = "verificationProgress", skip_serializing_if = "Option::is_none")]
    pub verification_progress: Option<f64>,
}

impl ApplicationServerInfoNodeStatusData {
    /// Detailed sync status of the internal full node
    pub fn new() -> ApplicationServerInfoNodeStatusData {
        ApplicationServerInfoNodeStatusData {
            headers: None,
            blocks: None,
            verification_progress: None,
        }
    }
}


