/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AssetPairData : An asset pair we can trade.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AssetPairData {
    /// The name of the asset pair.
    #[serde(rename = "pair", skip_serializing_if = "Option::is_none")]
    pub pair: Option<String>,
    /// The smallest amount we can buy or sell.
    #[serde(rename = "minimumTradeQty", skip_serializing_if = "Option::is_none")]
    pub minimum_trade_qty: Option<f32>,
}

impl AssetPairData {
    /// An asset pair we can trade.
    pub fn new() -> AssetPairData {
        AssetPairData {
            pair: None,
            minimum_trade_qty: None,
        }
    }
}


