/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AssetBalanceData : An asset and it's qty.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AssetBalanceData {
    /// An asset.
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    /// The quantity changed of the asset. Can be positive or negative.
    #[serde(rename = "qty", skip_serializing_if = "Option::is_none")]
    pub qty: Option<f32>,
}

impl AssetBalanceData {
    /// An asset and it's qty.
    pub fn new() -> AssetBalanceData {
        AssetBalanceData {
            asset: None,
            qty: None,
        }
    }
}


