/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreatePayoutRequest {
    /// The destination of the payout (can be an address or a BIP21 url)
    #[serde(rename = "destination", skip_serializing_if = "Option::is_none")]
    pub destination: Option<String>,
    /// The amount of the payout in the currency of the pull payment (eg. USD).
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    /// The payment method of the payout
    #[serde(rename = "paymentMethod", skip_serializing_if = "Option::is_none")]
    pub payment_method: Option<String>,
}

impl CreatePayoutRequest {
    pub fn new() -> CreatePayoutRequest {
        CreatePayoutRequest {
            destination: None,
            amount: None,
            payment_method: None,
        }
    }
}


