/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CustodiansGetStoreCustodianAccountDepositAddress200Response : A bitcoin address belonging to the custodian



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CustodiansGetStoreCustodianAccountDepositAddress200Response {
    /// The address to deposit your funds.
    #[serde(rename = "depositAddress", skip_serializing_if = "Option::is_none")]
    pub deposit_address: Option<String>,
}

impl CustodiansGetStoreCustodianAccountDepositAddress200Response {
    /// A bitcoin address belonging to the custodian
    pub fn new() -> CustodiansGetStoreCustodianAccountDepositAddress200Response {
        CustodiansGetStoreCustodianAccountDepositAddress200Response {
            deposit_address: None,
        }
    }
}


