/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CustodianAccountData {
    /// The unique code of the customer's account with this custodian. The format depends on the custodian.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The store ID.
    #[serde(rename = "storeId", skip_serializing_if = "Option::is_none")]
    pub store_id: Option<String>,
    /// The code for the custodian.
    #[serde(rename = "custodianCode", skip_serializing_if = "Option::is_none")]
    pub custodian_code: Option<String>,
    /// The name of the custodian account.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// A real-time loaded list of all assets (fiat and crypto) on this custodian and the quantity held in the account. Assets with qty 0 can be omitted.
    #[serde(rename = "assetBalances", skip_serializing_if = "Option::is_none")]
    pub asset_balances: Option<Vec<crate::models::AssetBalanceData>>,
    /// The configuration of this custodian account. Specific contents depend on the custodian and your access permissions.
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<serde_json::Value>,
}

impl CustodianAccountData {
    pub fn new() -> CustodianAccountData {
        CustodianAccountData {
            id: None,
            store_id: None,
            custodian_code: None,
            name: None,
            asset_balances: None,
            config: None,
        }
    }
}


