/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InvoiceMetadataAnyOf2 {
    #[serde(rename = "buyerName", skip_serializing_if = "Option::is_none")]
    pub buyer_name: Option<String>,
}

impl InvoiceMetadataAnyOf2 {
    pub fn new() -> InvoiceMetadataAnyOf2 {
        InvoiceMetadataAnyOf2 {
            buyer_name: None,
        }
    }
}


