/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InvoiceMetadataAnyOf13 {
    #[serde(rename = "physical", skip_serializing_if = "Option::is_none")]
    pub physical: Option<String>,
}

impl InvoiceMetadataAnyOf13 {
    pub fn new() -> InvoiceMetadataAnyOf13 {
        InvoiceMetadataAnyOf13 {
            physical: None,
        }
    }
}


