/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InvoiceMetadataAnyOf3 {
    #[serde(rename = "buyerEmail", skip_serializing_if = "Option::is_none")]
    pub buyer_email: Option<String>,
}

impl InvoiceMetadataAnyOf3 {
    pub fn new() -> InvoiceMetadataAnyOf3 {
        InvoiceMetadataAnyOf3 {
            buyer_email: None,
        }
    }
}


