/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InvoiceDataBase {
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<crate::models::InvoiceMetadata>>,
    #[serde(rename = "checkout", skip_serializing_if = "Option::is_none")]
    pub checkout: Option<Box<crate::models::CheckoutOptions>>,
    #[serde(rename = "receipt", skip_serializing_if = "Option::is_none")]
    pub receipt: Option<Box<crate::models::ReceiptOptions>>,
}

impl InvoiceDataBase {
    pub fn new() -> InvoiceDataBase {
        InvoiceDataBase {
            metadata: None,
            checkout: None,
            receipt: None,
        }
    }
}


