/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InvoiceMetadataAnyOf9 {
    #[serde(rename = "buyerAddress2", skip_serializing_if = "Option::is_none")]
    pub buyer_address2: Option<String>,
}

impl InvoiceMetadataAnyOf9 {
    pub fn new() -> InvoiceMetadataAnyOf9 {
        InvoiceMetadataAnyOf9 {
            buyer_address2: None,
        }
    }
}


