/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InvoiceMetadataAnyOf {
    /// You can use this property to store the ID of an external system. We allow you to search in the invoice list based on this ID.
    #[serde(rename = "orderId", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<String>,
    /// You can use this property to store the URL to the order of an external system. This makes navigating to the order easier.
    #[serde(rename = "orderUrl", skip_serializing_if = "Option::is_none")]
    pub order_url: Option<String>,
}

impl InvoiceMetadataAnyOf {
    pub fn new() -> InvoiceMetadataAnyOf {
        InvoiceMetadataAnyOf {
            order_id: None,
            order_url: None,
        }
    }
}


