/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InvoiceMetadataAnyOf8 {
    #[serde(rename = "buyerAddress1", skip_serializing_if = "Option::is_none")]
    pub buyer_address1: Option<String>,
}

impl InvoiceMetadataAnyOf8 {
    pub fn new() -> InvoiceMetadataAnyOf8 {
        InvoiceMetadataAnyOf8 {
            buyer_address1: None,
        }
    }
}


