/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InvoiceMetadataAnyOf5 {
    #[serde(rename = "buyerZip", skip_serializing_if = "Option::is_none")]
    pub buyer_zip: Option<String>,
}

impl InvoiceMetadataAnyOf5 {
    pub fn new() -> InvoiceMetadataAnyOf5 {
        InvoiceMetadataAnyOf5 {
            buyer_zip: None,
        }
    }
}


