/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// InvoiceStatusMark : 

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InvoiceStatusMark {
    #[serde(rename = "Invalid")]
    Invalid,
    #[serde(rename = "Settled")]
    Settled,

}

impl ToString for InvoiceStatusMark {
    fn to_string(&self) -> String {
        match self {
            Self::Invalid => String::from("Invalid"),
            Self::Settled => String::from("Settled"),
        }
    }
}

impl Default for InvoiceStatusMark {
    fn default() -> InvoiceStatusMark {
        Self::Invalid
    }
}




