/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// InvoiceType : 

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InvoiceType {
    #[serde(rename = "Standard")]
    Standard,
    #[serde(rename = "TopUp")]
    TopUp,

}

impl ToString for InvoiceType {
    fn to_string(&self) -> String {
        match self {
            Self::Standard => String::from("Standard"),
            Self::TopUp => String::from("TopUp"),
        }
    }
}

impl Default for InvoiceType {
    fn default() -> InvoiceType {
        Self::Standard
    }
}




