/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// InvoicePaymentMethodDataModelAdditionalDataAnyOf : LNURL Pay information



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InvoicePaymentMethodDataModelAdditionalDataAnyOf {
    /// The provided comment to a LNUrl payment with comments enabled
    #[serde(rename = "providedComment", skip_serializing_if = "Option::is_none")]
    pub provided_comment: Option<String>,
    /// The consumed lightning address of a LN Address payment
    #[serde(rename = "consumedLightningAddress", skip_serializing_if = "Option::is_none")]
    pub consumed_lightning_address: Option<String>,
}

impl InvoicePaymentMethodDataModelAdditionalDataAnyOf {
    /// LNURL Pay information
    pub fn new() -> InvoicePaymentMethodDataModelAdditionalDataAnyOf {
        InvoicePaymentMethodDataModelAdditionalDataAnyOf {
            provided_comment: None,
            consumed_lightning_address: None,
        }
    }
}


