/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// InvoiceAdditionalStatus : An additional status that describes why an invoice is in its current status.

/// An additional status that describes why an invoice is in its current status.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InvoiceAdditionalStatus {
    #[serde(rename = "None")]
    None,
    #[serde(rename = "PaidLate")]
    PaidLate,
    #[serde(rename = "PaidPartial")]
    PaidPartial,
    #[serde(rename = "Marked")]
    Marked,
    #[serde(rename = "Invalid")]
    Invalid,
    #[serde(rename = "PaidOver")]
    PaidOver,

}

impl ToString for InvoiceAdditionalStatus {
    fn to_string(&self) -> String {
        match self {
            Self::None => String::from("None"),
            Self::PaidLate => String::from("PaidLate"),
            Self::PaidPartial => String::from("PaidPartial"),
            Self::Marked => String::from("Marked"),
            Self::Invalid => String::from("Invalid"),
            Self::PaidOver => String::from("PaidOver"),
        }
    }
}

impl Default for InvoiceAdditionalStatus {
    fn default() -> InvoiceAdditionalStatus {
        Self::None
    }
}




