/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// InvoicePaymentMethodDataModelAdditionalData : Additional data provided by the payment method.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InvoicePaymentMethodDataModelAdditionalData {
    /// The provided comment to a LNUrl payment with comments enabled
    #[serde(rename = "providedComment", skip_serializing_if = "Option::is_none")]
    pub provided_comment: Option<String>,
    /// The consumed lightning address of a LN Address payment
    #[serde(rename = "consumedLightningAddress", skip_serializing_if = "Option::is_none")]
    pub consumed_lightning_address: Option<String>,
}

impl InvoicePaymentMethodDataModelAdditionalData {
    /// Additional data provided by the payment method.
    pub fn new() -> InvoicePaymentMethodDataModelAdditionalData {
        InvoicePaymentMethodDataModelAdditionalData {
            provided_comment: None,
            consumed_lightning_address: None,
        }
    }
}


