/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InvoiceMetadataAnyOf4 {
    #[serde(rename = "buyerCountry", skip_serializing_if = "Option::is_none")]
    pub buyer_country: Option<String>,
}

impl InvoiceMetadataAnyOf4 {
    pub fn new() -> InvoiceMetadataAnyOf4 {
        InvoiceMetadataAnyOf4 {
            buyer_country: None,
        }
    }
}


