/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InvoiceMetadataAnyOf6 {
    #[serde(rename = "buyerState", skip_serializing_if = "Option::is_none")]
    pub buyer_state: Option<String>,
}

impl InvoiceMetadataAnyOf6 {
    pub fn new() -> InvoiceMetadataAnyOf6 {
        InvoiceMetadataAnyOf6 {
            buyer_state: None,
        }
    }
}


