/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LightningInvoiceStatus : 

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LightningInvoiceStatus {
    #[serde(rename = "Unpaid")]
    Unpaid,
    #[serde(rename = "Paid")]
    Paid,
    #[serde(rename = "Expired")]
    Expired,

}

impl ToString for LightningInvoiceStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Unpaid => String::from("Unpaid"),
            Self::Paid => String::from("Paid"),
            Self::Expired => String::from("Expired"),
        }
    }
}

impl Default for LightningInvoiceStatus {
    fn default() -> LightningInvoiceStatus {
        Self::Unpaid
    }
}




