/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LightningNodeInformationData {
    /// Node URIs to connect to this node in the form `pubkey@endpoint[:port]`
    #[serde(rename = "nodeURIs", skip_serializing_if = "Option::is_none")]
    pub node_uris: Option<Vec<String>>,
    /// The block height of the lightning node
    #[serde(rename = "blockHeight", skip_serializing_if = "Option::is_none")]
    pub block_height: Option<i32>,
}

impl LightningNodeInformationData {
    pub fn new() -> LightningNodeInformationData {
        LightningNodeInformationData {
            node_uris: None,
            block_height: None,
        }
    }
}


