/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LightningNodeBalanceData {
    #[serde(rename = "onchain", skip_serializing_if = "Option::is_none")]
    pub onchain: Option<crate::models::OnchainBalanceData>,
    #[serde(rename = "offchain", skip_serializing_if = "Option::is_none")]
    pub offchain: Option<crate::models::OffchainBalanceData>,
}

impl LightningNodeBalanceData {
    pub fn new() -> LightningNodeBalanceData {
        LightningNodeBalanceData {
            onchain: None,
            offchain: None,
        }
    }
}


