/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LightningPaymentStatus : 

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LightningPaymentStatus {
    #[serde(rename = "Unknown")]
    Unknown,
    #[serde(rename = "Pending")]
    Pending,
    #[serde(rename = "Complete")]
    Complete,
    #[serde(rename = "Failed")]
    Failed,

}

impl ToString for LightningPaymentStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Unknown => String::from("Unknown"),
            Self::Pending => String::from("Pending"),
            Self::Complete => String::from("Complete"),
            Self::Failed => String::from("Failed"),
        }
    }
}

impl Default for LightningPaymentStatus {
    fn default() -> LightningPaymentStatus {
        Self::Unknown
    }
}




