/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LnurlPayPaymentMethodDataAllOf {
    /// Whether the payment method is enabled. Note that this can only enabled when a Lightning Network payment method is available and enabled
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Crypto code of the payment method
    #[serde(rename = "cryptoCode", skip_serializing_if = "Option::is_none")]
    pub crypto_code: Option<String>,
}

impl LnurlPayPaymentMethodDataAllOf {
    pub fn new() -> LnurlPayPaymentMethodDataAllOf {
        LnurlPayPaymentMethodDataAllOf {
            enabled: None,
            crypto_code: None,
        }
    }
}


