/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LockUserRequest {
    /// Whether to lock or unlock the user
    #[serde(rename = "locked", skip_serializing_if = "Option::is_none")]
    pub locked: Option<bool>,
}

impl LockUserRequest {
    pub fn new() -> LockUserRequest {
        LockUserRequest {
            locked: None,
        }
    }
}


