/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MarkInvoiceStatusRequest {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::models::InvoiceStatusMark>,
}

impl MarkInvoiceStatusRequest {
    pub fn new() -> MarkInvoiceStatusRequest {
        MarkInvoiceStatusRequest {
            status: None,
        }
    }
}


