/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OnChainPaymentMethodDataPreviewAllOf {
    /// Crypto code of the payment method
    #[serde(rename = "cryptoCode", skip_serializing_if = "Option::is_none")]
    pub crypto_code: Option<String>,
}

impl OnChainPaymentMethodDataPreviewAllOf {
    pub fn new() -> OnChainPaymentMethodDataPreviewAllOf {
        OnChainPaymentMethodDataPreviewAllOf {
            crypto_code: None,
        }
    }
}


