/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OnChainWalletTransactionData {
    /// The transaction id
    #[serde(rename = "transactionHash", skip_serializing_if = "Option::is_none")]
    pub transaction_hash: Option<String>,
    /// A comment linked to the transaction
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// The amount the wallet balance changed with this transaction
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    /// The hash of the block that confirmed this transaction. Null if still unconfirmed.
    #[serde(rename = "blockHash", skip_serializing_if = "Option::is_none")]
    pub block_hash: Option<String>,
    /// The height of the block that confirmed this transaction. Null if still unconfirmed.
    #[serde(rename = "blockHeight", skip_serializing_if = "Option::is_none")]
    pub block_height: Option<String>,
    /// The number of confirmations for this transaction
    #[serde(rename = "confirmations", skip_serializing_if = "Option::is_none")]
    pub confirmations: Option<String>,
    /// The time of the transaction
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<f32>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::models::TransactionStatus>,
    /// Labels linked to this transaction
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<Vec<crate::models::LabelData>>,
}

impl OnChainWalletTransactionData {
    pub fn new() -> OnChainWalletTransactionData {
        OnChainWalletTransactionData {
            transaction_hash: None,
            comment: None,
            amount: None,
            block_hash: None,
            block_height: None,
            confirmations: None,
            timestamp: None,
            status: None,
            labels: None,
        }
    }
}


