/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OnChainWalletOverviewData {
    /// The total current balance of the wallet
    #[serde(rename = "balance", skip_serializing_if = "Option::is_none")]
    pub balance: Option<String>,
    /// The current unconfirmed balance of the wallet
    #[serde(rename = "unconfirmedBalance", skip_serializing_if = "Option::is_none")]
    pub unconfirmed_balance: Option<String>,
    /// The current confirmed balance of the wallet
    #[serde(rename = "confirmedBalance", skip_serializing_if = "Option::is_none")]
    pub confirmed_balance: Option<String>,
}

impl OnChainWalletOverviewData {
    pub fn new() -> OnChainWalletOverviewData {
        OnChainWalletOverviewData {
            balance: None,
            unconfirmed_balance: None,
            confirmed_balance: None,
        }
    }
}


