/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OnChainWalletFeeRateData {
    /// The fee rate (sats per byte) based on the wallet's configured recommended block confirmation target
    #[serde(rename = "feerate", skip_serializing_if = "Option::is_none")]
    pub feerate: Option<f32>,
}

impl OnChainWalletFeeRateData {
    pub fn new() -> OnChainWalletFeeRateData {
        OnChainWalletFeeRateData {
            feerate: None,
        }
    }
}


