/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OnChainPaymentMethodDataWithSensitiveDataAllOf {
    /// The mnemonic used to generate the wallet
    #[serde(rename = "mnemonic", skip_serializing_if = "Option::is_none")]
    pub mnemonic: Option<String>,
}

impl OnChainPaymentMethodDataWithSensitiveDataAllOf {
    pub fn new() -> OnChainPaymentMethodDataWithSensitiveDataAllOf {
        OnChainPaymentMethodDataWithSensitiveDataAllOf {
            mnemonic: None,
        }
    }
}


