/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OpenLightningChannelRequest {
    /// Node URI in the form `pubkey@endpoint[:port]`
    #[serde(rename = "nodeURI", skip_serializing_if = "Option::is_none")]
    pub node_uri: Option<String>,
    /// The amount to fund (in satoshi)
    #[serde(rename = "channelAmount", skip_serializing_if = "Option::is_none")]
    pub channel_amount: Option<String>,
    /// The amount to fund (in satoshi per byte)
    #[serde(rename = "feeRate", skip_serializing_if = "Option::is_none")]
    pub fee_rate: Option<f32>,
}

impl OpenLightningChannelRequest {
    pub fn new() -> OpenLightningChannelRequest {
        OpenLightningChannelRequest {
            node_uri: None,
            channel_amount: None,
            fee_rate: None,
        }
    }
}


