/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchOnChainTransactionRequest {
    /// Transaction comment
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// Transaction labels
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<Vec<String>>,
}

impl PatchOnChainTransactionRequest {
    pub fn new() -> PatchOnChainTransactionRequest {
        PatchOnChainTransactionRequest {
            comment: None,
            labels: None,
        }
    }
}


