/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PayoutProcessorData {
    /// unique identifier of the payout processor
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Human name of the payout processor
    #[serde(rename = "friendlyName", skip_serializing_if = "Option::is_none")]
    pub friendly_name: Option<String>,
    /// Supported, payment methods by this processor
    #[serde(rename = "paymentMethods", skip_serializing_if = "Option::is_none")]
    pub payment_methods: Option<Vec<String>>,
}

impl PayoutProcessorData {
    pub fn new() -> PayoutProcessorData {
        PayoutProcessorData {
            name: None,
            friendly_name: None,
            payment_methods: None,
        }
    }
}


