/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PermissionsMetadata200ResponseInner {
    /// The permission id
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Permissions included in this array are also granted by this permission
    #[serde(rename = "included", skip_serializing_if = "Option::is_none")]
    pub included: Option<Vec<String>>,
}

impl PermissionsMetadata200ResponseInner {
    pub fn new() -> PermissionsMetadata200ResponseInner {
        PermissionsMetadata200ResponseInner {
            name: None,
            included: None,
        }
    }
}


