/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ProblemDetails : Description of an error happening during processing of the request



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProblemDetails {
    /// An error code describing the error
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// User friendly error message about the error
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl ProblemDetails {
    /// Description of an error happening during processing of the request
    pub fn new() -> ProblemDetails {
        ProblemDetails {
            code: None,
            message: None,
        }
    }
}


