/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReceiptOptions {
    /// A public page will be accessible once the invoice is settled. If null or unspecified, it will fallback to the store's settings. (The default store settings is true)
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Show the QR code of the receipt in the public receipt page. If null or unspecified, it will fallback to the store's settings. (The default store setting is true)
    #[serde(rename = "showQR", skip_serializing_if = "Option::is_none")]
    pub show_qr: Option<bool>,
    /// Show the payment list in the public receipt page. If null or unspecified, it will fallback to the store's settings. (The default store setting is true)
    #[serde(rename = "showPayments", skip_serializing_if = "Option::is_none")]
    pub show_payments: Option<bool>,
}

impl ReceiptOptions {
    pub fn new() -> ReceiptOptions {
        ReceiptOptions {
            enabled: None,
            show_qr: None,
            show_payments: None,
        }
    }
}


