/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TimeSpanMinutes : A span of times in minutes

pub type TimeSpanMinutes = u16;

/*#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TimeSpanMinutes {
}

impl TimeSpanMinutes {
    /// A span of times in minutes
    pub fn new() -> TimeSpanMinutes {
        TimeSpanMinutes {
        }
    }
}*/

