/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TradeRequestDataQty {
}

impl TradeRequestDataQty {
    pub fn new() -> TradeRequestDataQty {
        TradeRequestDataQty {
        }
    }
}


