/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TransactionStatus : 

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransactionStatus {
    #[serde(rename = "Unconfirmed")]
    Unconfirmed,
    #[serde(rename = "Confirmed")]
    Confirmed,

}

impl ToString for TransactionStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Unconfirmed => String::from("Unconfirmed"),
            Self::Confirmed => String::from("Confirmed"),
        }
    }
}

impl Default for TransactionStatus {
    fn default() -> TransactionStatus {
        Self::Unconfirmed
    }
}




