/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateInvoiceRequest {
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<crate::models::InvoiceMetadata>>,
}

impl UpdateInvoiceRequest {
    pub fn new() -> UpdateInvoiceRequest {
        UpdateInvoiceRequest {
            metadata: None,
        }
    }
}


