/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateLightningNetworkPaymentMethodRequestAllOf {
    /// Whether the payment method is enabled
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

impl UpdateLightningNetworkPaymentMethodRequestAllOf {
    pub fn new() -> UpdateLightningNetworkPaymentMethodRequestAllOf {
        UpdateLightningNetworkPaymentMethodRequestAllOf {
            enabled: None,
        }
    }
}


