/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateNotification {
    /// Sets the notification as seen/unseen. If left null, sets it to the opposite value
    #[serde(rename = "seen", skip_serializing_if = "Option::is_none")]
    pub seen: Option<bool>,
}

impl UpdateNotification {
    pub fn new() -> UpdateNotification {
        UpdateNotification {
            seen: None,
        }
    }
}


