/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ValidationProblemDetailsInner : A specific validation error on a json property



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ValidationProblemDetailsInner {
    /// The json path of the property which failed validation
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    /// User friendly error message about the validation
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl ValidationProblemDetailsInner {
    /// A specific validation error on a json property
    pub fn new() -> ValidationProblemDetailsInner {
        ValidationProblemDetailsInner {
            path: None,
            message: None,
        }
    }
}


