/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WebhookInvoiceInvalidEventAllOf {
    /// Whether the invoice have been manually marked as confirmed. If false, this invoice has received payments which could not confirm in time.
    #[serde(rename = "manuallyMarked", skip_serializing_if = "Option::is_none")]
    pub manually_marked: Option<bool>,
}

impl WebhookInvoiceInvalidEventAllOf {
    pub fn new() -> WebhookInvoiceInvalidEventAllOf {
        WebhookInvoiceInvalidEventAllOf {
            manually_marked: None,
        }
    }
}


