/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// WebhookDataBaseAuthorizedEvents : Which event should be received by this endpoint



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WebhookDataBaseAuthorizedEvents {
    /// If true, the endpoint will receive all events related to the store.
    #[serde(rename = "everything", skip_serializing_if = "Option::is_none")]
    pub everything: Option<bool>,
    /// If `everything` is false, the specific events that the endpoint is interested in. Current events are: `InvoiceCreated`, `InvoiceReceivedPayment`, `InvoiceProcessing`, `InvoiceExpired`, `InvoiceSettled`, `InvoiceInvalid`.
    #[serde(rename = "specificEvents", skip_serializing_if = "Option::is_none")]
    pub specific_events: Option<Vec<String>>,
}

impl WebhookDataBaseAuthorizedEvents {
    /// Which event should be received by this endpoint
    pub fn new() -> WebhookDataBaseAuthorizedEvents {
        WebhookDataBaseAuthorizedEvents {
            everything: None,
            specific_events: None,
        }
    }
}


