/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WebhookInvoiceSettledEventAllOf {
    /// Whether the invoice have been manually marked as confirmed
    #[serde(rename = "manuallyMarked", skip_serializing_if = "Option::is_none")]
    pub manually_marked: Option<bool>,
}

impl WebhookInvoiceSettledEventAllOf {
    pub fn new() -> WebhookInvoiceSettledEventAllOf {
        WebhookInvoiceSettledEventAllOf {
            manually_marked: None,
        }
    }
}


