/*
 * BTCPay Greenfield API
 *
 * A full API to use your BTCPay Server
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WithdrawalRequestData {
    /// The payment method (cryptocode + network) of the withdrawal.
    #[serde(rename = "paymentMethod", skip_serializing_if = "Option::is_none")]
    pub payment_method: Option<String>,
    /// The qty to withdraw.
    #[serde(rename = "qty", skip_serializing_if = "Option::is_none")]
    pub qty: Option<f32>,
}

impl WithdrawalRequestData {
    pub fn new() -> WithdrawalRequestData {
        WithdrawalRequestData {
            payment_method: None,
            qty: None,
        }
    }
}


